Added TicketCreation and re-worked Create
hiqdev/hipanel-module-ticket pull request #49
Opened 2021-06-03 14:20 UTC by Drakorgaur

2021-06-24 07:33 UTC, strorch requested changes

2021-06-24 07:33 UTC, strorch commented on tests/_support/Page/ticket/Create.php
> +    public function createTicket($ticketData)
а ти впевнений що це не зламає інші тести?

2021-06-24 07:33 UTC, strorch commented on tests/_support/Page/ticket/Create.php
> +    public function createTicket($ticketData)
тайпхінт тоже додай тоді

2021-06-24 07:33 UTC, strorch commented on tests/acceptance/admin/TicketCreationCest.php
> +    public function ensureICanCreateTicket(Admin $I, Example $example)
тайпхніт

2021-06-24 07:33 UTC, strorch commented on tests/acceptance/admin/TicketCreationCest.php
> +    private function fillMainTicketFields(Admin $I,Example $exampleTicket)
назва метода не правильна

2021-06-24 07:33 UTC, strorch commented on tests/acceptance/admin/TicketCreationCest.php
> +    private function fillMainTicketFields(Admin $I,Example $exampleTicket)
тайпхніт

2021-06-24 07:33 UTC, strorch commented on tests/acceptance/admin/TicketCreationCest.php
> +class TicketStatisticsCest
а чого тікет статістік тест, якшо ти просто в ньому створюєщ тікет???? такий тест вже є

2021-06-24 11:01 UTC, Drakorgaur commented on tests/_support/Page/ticket/Create.php
> +    public function createTicket($ticketData)
![image](https://user-images.githubusercontent.com/83531949/123252021-7a116080-d4f4-11eb-8b5f-ba4118bd1754.png)
Тесты уже должны быть поломаны, т.к. то что я смазал не задает реципиента.

2021-06-24 11:05 UTC, Drakorgaur commented on tests/_support/Page/ticket/Create.php
> +    public function createTicket($ticketData)
так же тут же хочу сказать, что я не видел тесты, которые создают тикет. Да, вот щас порылся и нашел. Прост думал, что TicketCest проверит лишь то что работает  главная страница.
Я тогда предлагаю - я переделаю (добавлю реципиента) в TicketCest, а этот удалю.(ПР оставлю, чтоб Create не переписывать). 
Ок?

2021-06-25 08:02 UTC, strorch commented
обсудили в лічькі, жду правок

2021-06-29 07:26 UTC, strorch commented on tests/acceptance/client/TicketCest.php
> +                'recipient' => null,
```suggestion
```
це можна тоді просто не писать

2021-06-29 07:27 UTC, strorch approved these changes

2021-06-29 07:28 UTC, merged