Ticket statistics
hiqdev/hipanel-module-ticket pull request #6
Opened 2018-03-18 15:28 UTC by bladeroot

2018-03-18 19:08 UTC, hiqsol approved these changes
Дима ещё глянет и замержит.

2018-03-18 19:09 UTC, hiqsol commented
Эээ... звёздочку поставь!

2018-03-19 09:30 UTC, SilverFire requested changes

2018-03-19 09:30 UTC, SilverFire commented on src/grid/StatisticGridView.php
> +                    foreach (explode(",", $model->thread_ids) as $thread) {
я бы использовал тут виджет ArraySpoiler

2018-03-19 09:30 UTC, SilverFire commented on src/views/statistic/index.php
> +.list-inline {
Сделай отдельный ассет [тут](https://github.com/hiqdev/hipanel-module-ticket/tree/master/src/assets)

2018-03-19 09:30 UTC, SilverFire commented on src/views/statistic/_search.php
> + * @var \hipanel\widgets\AdvancedSearch
`@var \hipanel\widgets\AdvancedSearch $search`

2018-03-19 09:30 UTC, SilverFire commented on src/views/statistic/_search.php
> + * @var \yii\web\View
`@var \yii\web\View $this`

2018-03-19 09:30 UTC, SilverFire commented on src/controllers/StatisticController.php
> +use hisite\modules\news\models\ArticleData;
Убери неиспользованные use

2018-03-19 09:30 UTC, SilverFire commented on src/controllers/StatisticController.php
> +    public function actions()
Нужно добавить accessControl. Пример смотри [тут](https://github.com/hiqdev/hipanel-module-ticket/blob/master/src/controllers/TicketController.php#L63)

2018-03-19 13:32 UTC, bladeroot commented on src/grid/StatisticGridView.php
> +                    foreach (explode(",", $model->thread_ids) as $thread) {
Я пока не использую... Возможно дойдут руки и я сделаю еще и подтягивание затраченого времени к каждому тикету. И при наведении будет отображено затраченое время в тикете за указанный период (по умолчанию в текущем месяце). Для админов же будет время, которое они вписали в тикет

2018-03-19 15:29 UTC, hiqsol commented
access control ещё добавь и замержу

2018-03-19 15:32 UTC, SilverFire commented
Добавил же https://github.com/hiqdev/hipanel-module-ticket/pull/6/commits/e72c04f25f8e5a837403c3e53c12a529b35ea83f#diff-baaf8cd02a3ce7cfcb0c46e83f27a76aR24

2018-03-19 15:32 UTC, SilverFire approved these changes

2018-03-22 19:38 UTC, merged